### ISSUE TITLE
Constraint -Infinity as LHS 

### ISSUE THREAD

**Issue by glanch** [scipopt/SCIPpp#26]
As far as I understand the code, all constraints have a default LHS of 0. How would I achieve a LHS of -Infinity, e.g. if I want to create a constraint `-Infinity <= x <= 42` whereas a negative value of `x` should be feasible w.r.t. this constraint? In my case I could compute a lower bound, but I don't want to worry about this.

Best, glanch

**Comment by hedtke** [comment]
Hi. By passing an empty optional, the lower bound -inf is used, for the upper bound then +inf is used. For your example `-inf <= x <= 42` you would write

```cpp
Model model("Simple");
auto x = model.addVar("x", 1, VarType::CONTINUOUS, std::nullopt, 42);
```

**Comment by hedtke** [comment]
This should be possible, if not, it is a bug. Simply add a constraint like this:

```cpp
model.addConstr(x + y <= 42, "capacityRight");
```
